version: "3"
services:
  sender:
    build: .
    command: python src/run.py
    env_file:
     - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=sender_pwd
      - POSTGRES_USER=sender_usr
      - POSTGRES_DB=sender_db
