version: "3"

services:
  sender:
    command: python src/run.py
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=sender_db
      - POSTGRES_USER=sender_usr
      - POSTGRES_PASSWORD=sender_pwd
